# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-05 00:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('schedule_version', models.CharField(blank=True, default='0.0', max_length=50)),
                ('acronym', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='No title yet', max_length=100)),
                ('start', models.DateField(blank=True, default='1970-01-01')),
                ('end', models.DateField(blank=True, default='1970-01-01')),
                ('timeslot_duration', models.TimeField(blank=True, default='00:15')),
                ('days', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('schedule_xml_link', models.URLField()),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('building', models.CharField(blank=True, default='', max_length=30)),
                ('ftp_startfolder', models.CharField(blank=True, default='', max_length=100)),
                ('hashtag', models.CharField(blank=True, default='', max_length=10)),
                ('subfolder_to_find_the_filenames', models.CharField(blank=True, default='', max_length=20)),
                ('speaker_json_link', models.URLField(blank=True, default='')),
                ('speaker_json_version', models.CharField(blank=True, default='0.0', max_length=50)),
                ('blacklisted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event_Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField(blank=True, default='1970-01-01')),
                ('day_start', models.DateTimeField(blank=True, default='1970-01-01 00:00+01:00')),
                ('day_end', models.DateTimeField(blank=True, default='1970-01-01 00:00+01:00')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folders_Extensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('subfolder', models.CharField(blank=True, default='', max_length=10)),
                ('file_extension', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('language_en', models.CharField(default='', max_length=40)),
                ('language_de', models.CharField(blank=True, default='', max_length=40)),
                ('lang_amara_short', models.CharField(default='', max_length=15, unique=True)),
                ('lang_short_srt', models.CharField(blank=True, default='', max_length=15)),
                ('language_native', models.CharField(blank=True, default='', max_length=40)),
                ('amara_order', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('lang_code_media', models.CharField(blank=True, default='', max_length=3)),
                ('lang_code_iso_639_1', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, default='Link title', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('room', models.CharField(default='kein Raum', max_length=30)),
                ('building', models.CharField(default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('frab_id', models.PositiveSmallIntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=50)),
                ('abstract', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('doppelgaenger_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.Speaker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speaker_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True)),
                ('speaker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='www.Speaker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('state_de', models.CharField(max_length=100)),
                ('state_en', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('time_delta', models.FloatField(blank=True, null=True)),
                ('average_wpm', models.FloatField(blank=True, null=True)),
                ('average_spm', models.FloatField(blank=True, null=True)),
                ('recalculate_statistics', models.BooleanField(default=False)),
                ('n_most_frequent_words', models.TextField(default='{}')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Event')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics_Raw_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('time_delta', models.FloatField(blank=True, null=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('recalculate_statistics', models.BooleanField(default=False)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Speaker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics_Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('time_delta', models.FloatField(blank=True, null=True)),
                ('average_wpm', models.FloatField(blank=True, null=True)),
                ('average_spm', models.FloatField(blank=True, null=True)),
                ('recalculate_statistics', models.BooleanField(default=False)),
                ('n_most_frequent_words', models.TextField(default='{}')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Language')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Speaker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('is_original_lang', models.BooleanField(default=False)),
                ('revision', models.PositiveSmallIntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('time_processed_transcribing', models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='')),
                ('time_processed_syncing', models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='')),
                ('time_quality_check_done', models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='')),
                ('time_processed_translating', models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='')),
                ('needs_automatic_syncing', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('needs_sync_to_ftp', models.BooleanField(default=False)),
                ('needs_removal_from_ftp', models.BooleanField(default=False)),
                ('tweet', models.BooleanField(default=False)),
                ('needs_sync_to_YT', models.BooleanField(default=False)),
                ('needs_removal_from_YT', models.BooleanField(default=False)),
                ('tweet_autosync_done', models.BooleanField(default=False)),
                ('last_changed_on_amara', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('yt_caption_id', models.CharField(blank=True, default='', max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Language')),
                ('state', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='www.States')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('frab_id_talk', models.PositiveSmallIntegerField(default=-1)),
                ('blacklisted', models.BooleanField(default=False)),
                ('link_to_logo', models.URLField(blank=True, default='')),
                ('date', models.DateTimeField(blank=True, default='1970-01-01 00:00:00+01:00')),
                ('start', models.TimeField(blank=True, default='11:00')),
                ('duration', models.TimeField(blank=True, default=datetime.time(0, 45))),
                ('title', models.CharField(blank=True, default='ohne Titel', max_length=150)),
                ('subtitle_talk', models.CharField(blank=True, default=' ', max_length=300)),
                ('abstract', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('pad_id', models.CharField(blank=True, default='', max_length=30)),
                ('link_to_writable_pad', models.URLField(blank=True, default='')),
                ('link_to_readable_pad', models.URLField(blank=True, default='')),
                ('link_to_video_file', models.URLField(blank=True, default='')),
                ('amara_key', models.CharField(blank=True, default='', max_length=20)),
                ('youtube_key', models.CharField(blank=True, max_length=20)),
                ('video_duration', models.TimeField(blank=True, default=datetime.time(0, 0))),
                ('slug', models.SlugField(blank=True, default='', max_length=200)),
                ('youtube_key_t_1', models.CharField(blank=True, default='', max_length=20)),
                ('youtube_key_t_2', models.CharField(blank=True, default='', max_length=20)),
                ('guid', models.CharField(blank=True, default='', max_length=40)),
                ('filename', models.SlugField(blank=True, default='', max_length=200)),
                ('time_delta', models.FloatField(blank=True, null=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('average_wpm', models.FloatField(blank=True, null=True)),
                ('average_spm', models.FloatField(blank=True, null=True)),
                ('recalculate_talk_statistics', models.BooleanField(default=False)),
                ('speakers_words', models.IntegerField(blank=True, null=True)),
                ('speakers_strokes', models.IntegerField(blank=True, null=True)),
                ('speakers_time_delta', models.FloatField(blank=True, null=True)),
                ('speakers_average_wpm', models.FloatField(blank=True, null=True)),
                ('speakers_average_spm', models.FloatField(blank=True, null=True)),
                ('recalculate_speakers_statistics', models.BooleanField(default=False)),
                ('n_most_frequent_words', models.TextField(default='{}')),
                ('n_most_frequent_words_speakers', models.TextField(default='{}')),
                ('day', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='www.Event_Days')),
                ('event', models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, to='www.Event')),
                ('orig_language', models.ForeignKey(blank=True, default=287, on_delete=django.db.models.deletion.CASCADE, to='www.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Talk_Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('time_delta', models.FloatField(blank=True, null=True)),
                ('average_wpm', models.FloatField(blank=True, null=True)),
                ('average_spm', models.FloatField(blank=True, null=True)),
                ('recalculate_statistics', models.BooleanField(default=False)),
                ('n_most_frequent_words', models.TextField(default='{}')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Speaker')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Talk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('track', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='persons',
            field=models.ManyToManyField(blank=True, default=None, through='www.Talk_Persons', to='www.Speaker'),
        ),
        migrations.AddField(
            model_name='talk',
            name='room',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='www.Rooms'),
        ),
        migrations.AddField(
            model_name='talk',
            name='track',
            field=models.ForeignKey(blank=True, default=40, on_delete=django.db.models.deletion.CASCADE, to='www.Tracks'),
        ),
        migrations.AddField(
            model_name='talk',
            name='type_of',
            field=models.ForeignKey(blank=True, default=9, on_delete=django.db.models.deletion.CASCADE, to='www.Type_of'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Talk'),
        ),
        migrations.AddField(
            model_name='statistics_raw_data',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Talk'),
        ),
        migrations.AddField(
            model_name='links',
            name='talk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='www.Talk'),
        ),
        migrations.AddField(
            model_name='event',
            name='ftp_subfolders_extensions',
            field=models.ManyToManyField(blank=True, default=None, to='www.Folders_Extensions'),
        ),
    ]
