# Generated by Django 2.1.4 on 2019-01-02 20:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='cdn_subtitles_root_folder',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='subfolder_in_sync_folder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='autotiming_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='needs_removal_from_sync_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='needs_sync_to_sync_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='amara_activity_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='talk',
            name='amara_complete_update_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='talk',
            name='amara_update_interval',
            field=models.TimeField(blank=True, default='00:10'),
        ),
        migrations.AddField(
            model_name='talk',
            name='has_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='needs_complete_amara_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='next_amara_activity_check',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='blacklisted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='is_original_lang',
            field=models.BooleanField(default=False, verbose_name='original language'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='blacklisted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='talk',
            name='frab_id_talk',
            field=models.CharField(blank=True, default='-1', max_length=10),
        ),
        migrations.AddField(
            model_name='talk',
            name='transcript_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='www.Transcript'),
        ),
    ]
