# Generated by Django 2.1.4 on 2019-01-02 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20190102_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='amara_activity_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='amara_complete_update_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='next_amara_activity_check',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
