# Generated by Django 2.2.6 on 2019-10-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20190102_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='c3subtitles_youtube_key',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
